version: "3"
services:
  php:
    container_name: php
    build:
      context: ./
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile_nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./app:/var/www/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb:10.5.4
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    depends_on:
      - mariadb
    environment:
      - PMA_PORT=3306
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=example
